# Generated by Django 4.1.7 on 2023-06-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_view', '0010_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
