# Generated by Django 4.2.1 on 2023-06-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
